"""add role to user

Revision ID: 946cea4553ad
Revises: b5bc8092c6f4
Create Date: 2026-02-15 07:48:56.636586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '946cea4553ad'
down_revision: Union[str, Sequence[str], None] = 'b5bc8092c6f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first
    user_role = sa.Enum('ADMIN', 'MANAGER', 'STAFF', name='userrole')
    user_role.create(op.get_bind())

    # Add column as nullable first to avoid IntegrityError
    op.add_column('users', sa.Column('role', user_role, nullable=True))
    
    # Update existing rows with a default value (e.g., 'STAFF')
    op.execute("UPDATE users SET role = 'STAFF'")
    
    # Now set nullable=False
    op.alter_column('users', 'role', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')

    # Drop the enum type
    user_role = sa.Enum('ADMIN', 'MANAGER', 'STAFF', name='userrole')
    user_role.drop(op.get_bind())
    # ### end Alembic commands ###
